### ISSUE TITLE
Players swapping borrowed time in duos allows them to both have it temporarily

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#171]
This seems to work with all passives including ones like reincarnation.
Usually lasts for about 60 seconds from what I've but is hard to tell.

**Comment by Draze22** [comment]
To be clear when the ability gets swapped only 1 player will have the passive but the other player will still technically gets the benefits of the passive despite not appearing to have the ability.

**Comment by SanctusAnimus** [comment]
fixed with next update

**Comment by Draze22** [comment]
This is not fully fixed, just played a game of duos where swapping borrowed time allowed it to passively activate for the player that gave it to their partner.

**Comment by SanctusAnimus** [comment]
Borrowed time is not a passive, and disabling active abilities has consequences, so for now leaving it as it is for now.

**Comment by Draze22** [comment]
Closing this since we haven't had any reports of this for a long time.
