### ISSUE TITLE
Disconnected or abandoned players win matches 

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/custom_hero_clash_issues#384]
![Screenshot_20200530-075227](https://user-images.githubusercontent.com/16277198/83308699-b10e3780-a24a-11ea-897d-2ce7ad38505f.jpg)
Something to do with how the game calculates winners. It's allowing disconnected players to rank first.

**Comment by AustraliaIsMyCity** [comment]
afaik this has been fixed

**Comment by Draze22** [comment]
Still getting occasional reports of this bug occurring.

![image](https://user-images.githubusercontent.com/63279022/93010100-f07b4c80-f5cb-11ea-931e-7f4791f47d4d.png)
![image](https://user-images.githubusercontent.com/63279022/93010101-f96c1e00-f5cb-11ea-9811-6353d5406a8b.png)

**Comment by Draze22** [comment]
This bug is caused by a player disconnecting before the hero picking phase starts and connecting after it ends.

**Comment by AustraliaIsMyCity** [comment]
f i x e d
