### ISSUE TITLE
Networth doesn't display accurately.

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#77]
Currently the networth indicator at the top of the screen doesn't update when you sell items or buy and use retraining books/pages. Not sure if any of this is intended but it causes players networths to often be wildly different to what is displayed to other players. This could also potentially affect who receives retraining books/pages or more likely it will just make players confused as to why they did/didn't get them.

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/79035547-0b075f00-7c03-11ea-877c-0882cfe595db.png)

**Comment by AustraliaIsMyCity** [comment]
That day/night timer thing is having fun

**Comment by Draze22** [comment]
This is another example of networth not displaying accurately but this particular case jas happened twice to my knowledge and has an unknown cause. Both times the player reporting it thought the team was cheating but it ended up being clear it was a visual error.

![image](https://user-images.githubusercontent.com/63279022/81563890-4485e280-93da-11ea-98c3-4c1e96387204.png)

**Comment by Sheodar** [comment]
Should be fixed in new UI i think.

**Comment by Draze22** [comment]
Unless someone did something very recently to fix this it's still a problem.
